services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/posts
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]

  frontend:
    build:
      context: ./fronted
      args:
        VITE_API_URL: http://backend:8000
    ports:
      - "8000:8000"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  #! Port 5432 already occupied by another app in my cloud (Miguel)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
